# Generated by Django 4.1.3 on 2022-11-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city', models.TextField()),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=7)),
                ('country', models.TextField()),
                ('population', models.IntegerField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
