# Generated by Django 4.1.3 on 2022-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['-population']},
        ),
        migrations.AlterField(
            model_name='cities',
            name='lat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cities',
            name='lng',
            field=models.TextField(),
        ),
    ]
