# Generated by Django 4.1.3 on 2022-11-11 18:38

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('citydata', '0003_alter_cities_lat_alter_cities_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', django_cryptography.fields.encrypt(models.BigIntegerField(primary_key=True, serialize=False))),
                ('username', django_cryptography.fields.encrypt(models.TextField())),
                ('password', django_cryptography.fields.encrypt(models.TextField())),
            ],
        ),
    ]
