# Generated by Django 4.1.3 on 2022-11-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citydata', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
