# Generated by Django 4.1.3 on 2022-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('citydata', '0008_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='hub',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
