# Generated by Django 4.1.3 on 2022-11-17 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citydata', '0009_network_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='custom',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excl1', to='citydata.cities')),
                ('city2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excl2', to='citydata.cities')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
